version: "3.9"

services:

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  service-tasks:
    build: ./services/tasks
    container_name: service-tasks
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      PORT: 5001
      MONGO_URI: mongodb://mongo:27017/tasksdb

  service-users:
    build: ./services/users
    container_name: service-users
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    environment:
      PORT: 5002
      MONGO_URI: mongodb://mongo:27017/usersdb

  service-notify:
    build: ./services/notify
    container_name: service-notify
    ports:
      - "5003:5003"
    depends_on:
      - mongo
    environment:
      PORT: 5003
      MONGO_URI: mongodb://mongo:27017/notifydb

  service-compute:
    build: ./services/compute
    container_name: service-compute
    ports:
      - "5004:5004"
    environment:
      PORT: 5004

  service-gateway:
    build: ./services/gateway
    container_name: service-gateway
    ports:
      - "4000:4000"
    depends_on:
      - service-tasks
      - service-users
      - service-notify
      - service-compute
    environment:
      PORT: 4000
      TASKS_URL: http://service-tasks:5001
      USERS_URL: http://service-users:5002
      NOTIFY_URL: http://service-notify:5003
      COMPUTE_URL: http://service-compute:5004

volumes:
  mongo-data: