apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-users
  template:
    metadata:
      labels:
        app: service-users
    spec:
      containers:
        - name: service-users
          image: europe-west1-docker.pkg.dev/mern-grid-cluster/mern-repo/service-users:latest
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              value: "5002"
            - name: MONGO_URI
              value: "mongodb://mongo:27017/usersdb"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: service-users
spec:
  selector:
    app: service-users
  ports:
    - port: 5002
      targetPort: 5002
